apiVersion: v1
kind: Service
metadata:
  name: beer-service
  namespace: default
  labels:
    app: beer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 8080
      protocol: TCP
  selector:
    app: beer-service
  sessionAffinity: None
