---
apiVersion: v1
kind: Service
metadata:
  name: beer-service
  labels:
    app: beer-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31000
      targetPort: 8080
      protocol: TCP
  selector:
    app: beer-service
  sessionAffinity: None
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: beer-service
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: beer-service
    spec:
      containers:
      -  name: beer-service
         image: nevenc/beer-service-k8s:1.0.0
         ports:
         - containerPort: 8080
